[project]
name = "tagging_db"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "*"
click = "*"
sqlalchemy = "*"
fuzzywuzzy = "*"
pyyaml = "*"
rich = "*"
tqdm = "*"
pytest = "*"
argcomplete = "*"
pyinstaller = "*"
